baseURL = 'https://bjorgv.in/'
locale = 'en-us'
title = 'bjorgv.in'
theme = 'bjorgvin'
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]

copyright = "&copy;2026 bjorgv.in"

[params]
  author = "Björgvin Olafsson"
  description = "Björgvin Ólafsson — engineer building digital therapeutics at Sidekick Health, based in Stockholm."
  shareImage = "web-app-manifest-512x512.png"
  twitter = "bjorgvino"

  [params.image]
    enable = true
    file = "images/boland-background-web.jpg"

  [[params.links]]
    title = "Contact"

    [[params.links.list]]
      text = "LinkedIn"
      url = "https://www.linkedin.com/in/bjorgvino"
      new_tab = true

  [[params.links]]
    title = "Code"

    [[params.links.list]]
      text = "GitHub"
      url = "https://github.com/bjorgvino"
      new_tab = true

    [[params.links.list]]
      text = "Stack Overflow"
      url = "https://stackoverflow.com/users/2915101/bjorgvin"
      new_tab = true
